# Rscan Configuration File
# This file contains default settings for the Rscan network security scanner

[scan]
# Number of concurrent threads for scanning operations
threads = 100

# Global timeout for scan operations (seconds)
timeout = 30

# Rate limiting - maximum requests per second
rate_limit = 100

# Number of retries for failed operations
retries = 3

# User agent string for HTTP requests
user_agent = "Rscan/1.0 Security Scanner"

[discovery]
# ICMP ping timeout (milliseconds)
ping_timeout = 1000

# Port scan timeout per port (milliseconds)
port_scan_timeout = 3000

# TCP connection timeout (milliseconds)
tcp_connect_timeout = 5000

# UDP scan timeout (milliseconds)
udp_timeout = 2000

# Common ports to scan (used for quick scans)
common_ports = [
    21, 22, 23, 25, 53, 80, 110, 111, 135, 139, 143, 443, 993, 995, 
    1723, 3306, 3389, 5432, 5900, 8080
]

# Top 100 most common ports
top_ports = [
    1, 3, 4, 6, 7, 9, 13, 17, 19, 20, 21, 22, 23, 24, 25, 26, 30, 32, 33, 37,
    42, 43, 49, 53, 70, 79, 80, 81, 82, 83, 84, 85, 88, 89, 90, 99, 100, 106,
    109, 110, 111, 113, 119, 125, 135, 139, 143, 144, 146, 161, 163, 179, 199,
    211, 212, 222, 254, 255, 256, 259, 264, 280, 301, 306, 311, 340, 366, 389,
    406, 407, 416, 417, 425, 427, 443, 444, 445, 458, 464, 465, 481, 497, 500,
    512, 513, 514, 515, 524, 541, 543, 544, 545, 548, 554, 555, 563, 587, 593,
    616, 617, 625, 631, 636, 646, 648, 666, 667, 668, 683, 687, 691, 700, 705
]

[brute_force]
# Maximum number of authentication attempts per target
max_attempts = 1000

# Delay between brute force attempts (milliseconds)
delay_between_attempts = 100

# Connection timeout for brute force attempts (seconds)
connection_timeout = 10

# Services to include in brute force attacks
enabled_services = [
    "ssh", "ftp", "telnet", "smb", "rdp", 
    "mysql", "postgres", "mssql", "redis", "oracle"
]

[web_scan]
# Follow HTTP redirects
follow_redirects = true

# Maximum number of redirects to follow
max_redirects = 5

# HTTP request timeout (seconds)
request_timeout = 10

# Verify SSL certificates
verify_ssl = false

# Custom HTTP headers to include in requests
[web_scan.custom_headers]
# "X-Custom-Header" = "Custom-Value"

[exploit]
# Enable exploitation capabilities (WARNING: Use with caution!)
enabled = false

# Automatically attempt exploitation of discovered vulnerabilities
auto_exploit = false

# Timeout for payload execution (seconds)
payload_timeout = 30

# Reverse shell configuration (optional)
# reverse_shell_ip = "192.168.1.100"
# reverse_shell_port = 4444

[reporting]
# Output directory for reports
output_dir = "./reports"

# Report formats to generate
formats = ["Json", "Html"]

# Include raw scan data in reports
include_raw_data = true

# Compress output files
compress_output = false

[wordlists]
# Path to username wordlist
usernames = "./wordlists/usernames.txt"

# Path to password wordlist
passwords = "./wordlists/passwords.txt"

# Custom wordlists for specific services
[wordlists.custom_wordlists]
# "directories" = "./wordlists/directories.txt"
# "subdomains" = "./wordlists/subdomains.txt"

# Advanced Configuration Options

[advanced]
# Enable debug logging
debug = false

# Log file path (optional, logs to stdout if not specified)
# log_file = "./rscan.log"

# Maximum memory usage (MB)
max_memory = 1024

# Enable performance profiling
profiling = false

# Custom DNS servers (optional)
# dns_servers = ["8.8.8.8", "1.1.1.1"]

# Network interface to use for scanning (optional)
# interface = "eth0"

# Source IP address for scans (optional)
# source_ip = "192.168.1.100"

# Custom TCP/UDP source port range (optional)
# source_port_range = "1024-65535"

# Enable IPv6 scanning
ipv6_enabled = true

# Scan timing template (1-5, where 1 is slowest and 5 is fastest)
timing_template = 3

# Custom scan delays (milliseconds)
[advanced.timing]
# host_timeout = 30000
# scan_delay = 0
# max_retries = 3
# min_rate = 1
# max_rate = 1000

# Evasion techniques
[advanced.evasion]
# Fragment packets
fragment_packets = false

# Use decoy IP addresses
# decoy_ips = ["192.168.1.10", "192.168.1.20"]

# Randomize scan order
randomize_hosts = true

# Spoof source MAC address (requires root privileges)
# spoof_mac = "00:11:22:33:44:55"

# Use proxy for HTTP requests
# http_proxy = "http://proxy.example.com:8080"

# Use SOCKS proxy
# socks_proxy = "socks5://proxy.example.com:1080"

# Database Configuration (for storing scan results)
[database]
# Enable database storage
enabled = false

# Database type (sqlite, mysql, postgresql)
db_type = "sqlite"

# Database connection string
# connection_string = "rscan.db"

# For MySQL/PostgreSQL:
# connection_string = "mysql://user:password@localhost/rscan"
# connection_string = "postgresql://user:password@localhost/rscan"

# Notification Configuration
[notifications]
# Enable notifications
enabled = false

# Notification types
# email = "admin@example.com"
# slack_webhook = "https://hooks.slack.com/services/..."
# discord_webhook = "https://discord.com/api/webhooks/..."

# Evasion and Stealth Configuration
[evasion]
# Enable evasion techniques (WARNING: Use only for authorized testing!)
enabled = false

# Timing template (1-5):
# 1 = Paranoid (very slow, maximum stealth)
# 2 = Sneaky (slow, high stealth)
# 3 = Polite (normal speed, moderate stealth)
# 4 = Normal (fast, low stealth)
# 5 = Aggressive (very fast, minimal stealth)
timing_template = 3

# Randomize User-Agent strings
randomize_user_agents = true

# Use TOR network (requires TOR to be running on localhost:9050)
use_tor = false

# HTTP proxy (format: http://user:pass@host:port)
# http_proxy = "http://proxy.example.com:8080"

# SOCKS5 proxy (format: socks5://user:pass@host:port)
# socks_proxy = "socks5://proxy.example.com:1080"

# Rotate between multiple proxies
proxy_rotation = false

# Generate decoy traffic to mask real scanning
generate_decoy_traffic = false

# Randomize HTTP headers
randomize_headers = true

# Enable packet fragmentation (requires raw socket privileges)
fragment_packets = false

# Spoof MAC address (requires root privileges and specific interface)
# spoof_mac = "00:11:22:33:44:55"

# Randomize source ports for connections
source_port_randomization = true

# Decoy hosts for generating fake traffic
decoy_hosts = [
    "www.google.com",
    "www.microsoft.com", 
    "www.cloudflare.com",
    "www.amazon.com",
    "www.github.com"
]

# Maximum request rate (requests per second)
max_request_rate = 10

# Jitter percentage for timing randomization (0.0 - 1.0)
jitter_percentage = 0.3

# Plugin Configuration
[plugins]
# Enable plugin system
enabled = false

# Plugin directory
plugin_dir = "./plugins"

# Enabled plugins
enabled_plugins = []

# Plugin-specific configuration
[plugins.nmap]
enabled = false
# nmap_path = "/usr/bin/nmap"

[plugins.masscan]
enabled = false
# masscan_path = "/usr/bin/masscan"

[plugins.nuclei]
enabled = false
# nuclei_path = "/usr/bin/nuclei"
# templates_dir = "./nuclei-templates"
